### ISSUE TITLE
How to use with NestJS - code first approach

### ISSUE THREAD

**Issue by carlovanti** [Urigo/graphql-scalars#101]
Hi, I'm using [NestJS (code first approach)](https://docs.nestjs.com/graphql/scalars) to build my GraphQL server application.
The problem is that I don't know exactly how to use these scalars with that approach.
Do you have any suggestions?

**Comment by ardatan** [comment]
I think you should add our scalars in schema-first approach :)

**Comment by DoctorVoid** [comment]
Here is my workaround:

`import { PhoneNumberResolver } from 'graphql-scalars';`

and then use it in your field definition like this:
`@Field(()=> PhoneNumberResolver, {nullable: true})
  phoneNumber?: any`

Still looking for a way to safe-type it instead of using any

**Comment by ardatan** [comment]
`string`?
