### ISSUE TITLE
The EmailAddress config is named wrong

### ISSUE THREAD

**Issue by tandrewnichols** [Urigo/graphql-scalars#1023]
**Describe the bug**
The EmailAddress config uses GraphQLCurrencyConfig (probably copied from the Currency scalar) instead of GraphQLEmailAddressConfig.

I have a fix for this, but the PR template says to open an issue first, so here we are.

**To Reproduce**
Open src/scalars/EmailAddress.ts and observe the config export name.

**Expected behavior**
The name matches the actual type.

**Environment:**

Not relevant

**Comment by notrab** [comment]
Was just about to PR this too! Covering it in a video. @Urigo would you merge a PR that fixes this?

**Comment by ardatan** [comment]
It was merged already;
https://github.com/Urigo/graphql-scalars/commit/1a189fe0d9a3f3008d533b97c679e80697870b77
And I jsut released it v1.10.1!
