### ISSUE TITLE
Byte validation fails when it's a base64 encoded string containing '/'

### ISSUE THREAD

**Issue by mgiamberardino** [Urigo/graphql-scalars#1088]
**Describe the bug**
When using graphql-mesh and having a Byte type in the schemas request is failing because a base64 string validation even when base64 string is valid. 

Already debugged the issue and it's happening when the encoded string contains an `/` which is a valid base64 character.

**To Reproduce**

Test to reproduce:
```js
// Encoded base64 string containing an /
const slashByte = Buffer.from([
  82, 71, 57, 107, 90, 50, 86, 121, 99, 121, 66, 83, 100, 87, 120, 108, 73, 81,
  47, 97, 81, 61,
]);
...
const slashBase64String = slashByte.toString('base64');
...
describe('base64 containing /', () => {
  test('should return true when validating', () => {
    expect(GraphQLByte.parseValue(slashBase64String)).toEqual(slashByte);
  });
});
```

**Expected behavior**
Validation should not fail on valid base64 encoded strings containing `/`

**Environment:**

- OS:
- GraphQL Scalars Version:
- NodeJS:

**Additional context**
I'm creating this issue just to be linked to the PR fixing the same.

**Comment by ardatan** [comment]
Available in v1.11.1
