### ISSUE TITLE
[Question] about naming

### ISSUE THREAD

**Issue by galkin** [Urigo/graphql-scalars#110]
Why we use:
```
import { EmailAddressResolver } from 'graphql-scalars';
```
instead
```
import { EmailAddress } from 'graphql-scalars';
```

Can we have both?

**Comment by ardatan** [comment]
@galkin Why do you need that? It's just confusing to have only `EmailAddress`, but we have different names for `resolver` and `typeDefinition` which is more clear.

**Comment by galkin** [comment]
@ardatan, thank you.

**Comment by benhickson** [comment]
Sorry to re-open, but it seemed relevant - is there any difference between importing `GraphQLDateTime` and `DateTimeResolver` ? Why are both exported?

**Comment by galkin** [comment]
TypeResolver !== TypeDefenition
