### ISSUE TITLE
Add DID scalar

### ISSUE THREAD

**Issue by takashimamorino** [Urigo/graphql-scalars#1168]
**Is your feature request related to a problem? Please describe.**
I'm developing a product that deals with DID. I'm developing a product that handles did, and I'd like to use this in that product.

**Describe the solution you'd like**
I'd like to add something compliant with the spec.
see: https://www.w3.org/TR/2021/PR-did-core-20210803/#did-syntax

**Comment by ardatan** [comment]
We'd love to accept a PR for this new scalar!

**Comment by ardatan** [comment]
Available in v1.13.0 ! Thanks
