### ISSUE TITLE
Add Locale Scalar

### ISSUE THREAD

**Issue by syl-oh** [Urigo/graphql-scalars#1177]
**Is your feature request related to a problem? Please describe.**

Add a new scalar for Locale (Standard locale format, as specified in [IETF BCP 47](https://www.rfc-editor.org/info/bcp47)).
The Locale is usually use to set one user's preferred language / region when working with multilingual interface.

**Describe the solution you'd like**
Implement the new custom scalar following [RFC5646](https://www.rfc-editor.org/rfc/rfc5646.txt) (Tags for Identifying Languages) for `Locale`.
e.g. `en-US` is a valid Locale.

**Comment by ardatan** [comment]
Sounds cool! We'd love to accept a PR if someone wants to implement it!

**Comment by syl-oh** [comment]
I have opened a new PR @ardatan with the new locale scalar. #1179

**Comment by syl-oh** [comment]
Can't be added because it requires an external dependency.
