### ISSUE TITLE
EmailAddress throws error with code `INTERNAL_SERVER_ERROR`

### ISSUE THREAD

**Issue by AhmedBHameed** [Urigo/graphql-scalars#1192]
**Describe the bug**
I used the scalar for email address. If user pass invalid email graphql throws error. The code of the error is `INTERNAL_SERVER_ERROR` which make no sense when the data is invalid.

**To Reproduce**

```typescript
import {
  EmailAddressResolver,
  EmailAddressTypeDefinition as EMAIL_ADDRESS_TYPE_DEFINITION,
} from 'graphql-scalars';


gql`
	[...]

	  type Mutation {
	      forgotPasswordByEmail(email: EmailAddress!): Message
	  }

	[...]
`

const schema = makeExecutableSchema({
  typeDefs: mergeTypeDefs([
    'scalar RequiredString',
    EMAIL_ADDRESS_TYPE_DEFINITION,
  ]),
  resolvers: mergeResolvers([
    {EmailAddress: EmailAddressResolver},
  ]),
});

export default schema;
```

**Expected behavior**
I believe the error code should be `BAD_USER_INPUT` instead of `INTERNAL_SERVER_ERROR`.

**Environment:**

- OS: Linux
- GraphQL Scalars Version: 
```
    "graphql-scalars": "^1.13.1",
```
- NodeJS: v14.18.1

**Additional context**
The reason of my concern is that INTERNAL_SERVER_ERROR might be a failure inside our implementation but not related to user input in this case because simply we are handling such an error for this use case and should be something different rather than INTERNAL_SERVER_ERROR

**Comment by ardatan** [comment]
Could you share a reproduction on CodeSandbox because GraphQL scalars have nothing to do with server implementation actually?

**Comment by AhmedBHameed** [comment]
@ardatan 

Maybe wasn't so clear. I mean by "our implementation" is the hi end implementation which is my side basically (Hi end script).

However, this is a minimum reproducing here

https://codesandbox.io/s/stupefied-mahavira-fe1mr?file=/src/index.js

**Comment by AhmedBHameed** [comment]
Updating `package.json` dependencies resolve the issue.
GREAT!!!!
