### ISSUE TITLE
PhoneNumber doesn't support many valid E164 numbers

### ISSUE THREAD

**Issue by dhritzkiv** [Urigo/graphql-scalars#124]
For example:

- Singapore phone numbers are formatted as `+6569701665` (that's 10 numeric characters).
- Solomon Islands, the number `+67734700` is 8 numeric characters long.
- In Niue, `+6834999`, at 7 numeric characters

The regex used in this library, `/^\+\d{11,15}$/`, doesn't satisfy these numbers. The quickest solution would be to change to regex to `/^\+\d{7,15}$/` or more simply `/^\+\d{1,15}$/`.

Ideally, numbers can be passed through libphonenumber (either google's or catamphetamine's which is smaller) to check if they're possible. While that would require including a relatively large library (130kB+), this package is only expected to run on the server (I believe) so that could be allowable?

If the preferred solution is quickly fixing the regex, I can submit a PR, with updated tests.

**Comment by ardatan** [comment]
`libphonenumber` is pretty big for a one scalar. Regular Expression seems more optimized solution. I changed it to `/^\+?[1-9]\d{1,14}$/` which fits all three examples of yours.

**Comment by dhritzkiv** [comment]
@ardatan I think that's totally fair.

**Comment by ardatan** [comment]
Could you confirm with the alpha version?
`1.0.3-27dc195.0`

**Comment by dhritzkiv** [comment]
I won't be able to get to this until tomorrow at the earliest.

But from what I can tell, it looks good! Especially since the (new) tests pass.

**Comment by ardatan** [comment]
Available in v1.0.3!
