### ISSUE TITLE
String versions of date scalars

### ISSUE THREAD

**Issue by jlowcs** [Urigo/graphql-scalars#1275]
**Is your feature request related to a problem? Please describe.**

As the available data scalars implementations serialize dates to Date objects, when using Apollo we end up with a [difference of behavior between server-side and client-side](https://github.com/Urigo/graphql-scalars/discussions/957), the former serializing to Date objects, while the latter leaves them as ISO strings.

Even without that inconsistency, it makes the migration from non-maintained [graphql-iso-date](https://www.npmjs.com/package/graphql-iso-date) difficult because of the change in types.

**Describe the solution you'd like**

Providing Date scalars that serialize to an ISO string would be a big help. For instance, adding a `GraphQLDateTimeIsoString` and a `GraphQLDateIsoString`.

**Describe alternatives you've considered**

Alternatives are either:
- keep using [graphql-iso-date](https://www.npmjs.com/package/graphql-iso-date) with the risk of it not working with future graphql version, and having to use `npm install --force` because of peer dependencies
- copy/pasting the code from [graphql-iso-date](https://www.npmjs.com/package/graphql-iso-date) in our app
- forking [graphql-iso-date](https://www.npmjs.com/package/graphql-iso-date) and updating the peer deps
- finding a solution to handle scalars client-side, and update our codebase to expect Date objects instead of strings

None of those are great :/

**Comment by josiah-roberts** [comment]
+1, would really benefit from this.

**Comment by falkenhawk** [comment]
https://github.com/Urigo/graphql-scalars/pull/1641

**Comment by ardatan** [comment]
`LocalDateTime` scalar is available now!
