### ISSUE TITLE
Does not accept valid emails without a dot

### ISSUE THREAD

**Issue by JimishF** [Urigo/graphql-scalars#131]
Please update the regex for email.
 
Accordnig to this [https://en.wikipedia.org/wiki/Email_address#Examples](https://en.wikipedia.org/wiki/Email_address#Examples),
 `name@mailserver` should be accepted as a valid email address.
`<input type="email" />` also allows such emails.

**Comment by ardatan** [comment]
@JimishF Could you try it with the canary version?
`1.0.3-0562dd0.0`

**Comment by JimishF** [comment]
okay cheking.

**Comment by JimishF** [comment]
Its working fine in canary. Thanks. Waiting for the release.

**Comment by ardatan** [comment]
@JimishF Let's keep it open until we release it :)

**Comment by JimishF** [comment]
Okay :)

**Comment by ardatan** [comment]
Available in v1.0.3!
