### ISSUE TITLE
Add CountryCode scalar

### ISSUE THREAD

**Issue by pukuba** [Urigo/graphql-scalars#1323]
There's no scalar type to check the country code.

eg) US, CN, GN

Therefore, may I add the country code scalar based on [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) ?

**Comment by ardatan** [comment]
Sure we'd love to accept your PR :)

**Comment by pukuba** [comment]
I have opened a new PR @ardatan with the new CountryCode scalar. #1326

**Comment by flesler** [comment]
This scalar is documented as available on https://www.graphql-scalars.dev/docs/scalars/country-code
Yet it's not available even in the latest NPM release `1.14.1`. It's a bit confusing, I ended up using a `RegularExpression` as a temporary placeholder
