### ISSUE TITLE
Mongoose queries with filtering fields of type emailaddress fails

### ISSUE THREAD

**Issue by 12sam12** [Urigo/graphql-scalars#1337]
**Describe the bug**
Mongoose queries with filtering using fields of type graphql scalar emailaddress fails

**To Reproduce**
lets assume emailid field in the schema was designed with type of graphql-scalar emailaddress. But if I filter it through some other string it works. 
await User.findOne({
    'emailid': 'somethingvalid@email.com'
});
Above async call's promise returns null, when actually such a document exists within that collection.

**Expected behavior**
Matched document has to be returned

**Environment:**

- OS: Linux
- GraphQL Scalars Version:  "graphql-scalars": "^1.14.1"
- NodeJS:  v14.16.0
- Mongoose: mongoose@6.1.3

**Comment by ardatan** [comment]
Could you share a reproduction? I don't think I fully understand the issue.

**Comment by 12sam12** [comment]
const {emailid, password} = creds;
    const allUsers = await User.find({});
    console.log(allUsers);   // This statement prints all users added
    const userRes = await User.findOne({
        'emailid': emailid
    });   // after this statement userRes is null


![image](https://user-images.githubusercontent.com/13358855/147383542-191eb939-6536-40de-89e9-3b7f846d363b.png)

![image](https://user-images.githubusercontent.com/13358855/147383545-47f528b5-ba77-496f-a6f7-c44bf24c7f2e.png)

**Comment by ardatan** [comment]
I'm not sure I still understand the issue. Could you share a clear minimal reproduction on CodeSandbox or in a repo please?
Thanks.

**Comment by 12sam12** [comment]
I have updated the code above just now, pls look into it.

**Comment by ardatan** [comment]
Sorry that is not helpful. Please share a reproduction repo as I already said above.

**Comment by 12sam12** [comment]
Seriously arent you able to get some idea currently? The DB has a document matching those query filters, but still null is being returned. Why is that so?

**Comment by ardatan** [comment]
I am sorry I am not. I don't understand the relationship between your db query and GraphQL scalar. Again I need to ask a clear reproduction repository or a piece of **real** code that reproduces the issue.

**Comment by 12sam12** [comment]
I have updated the schema design as well. Sorry. I have too many files that cant be shared in a repo right now.

**Comment by ardatan** [comment]
We don't need your entire project. We just need a **minimal** version that reproduces the issue.

**Comment by 12sam12** [comment]
Ya I understand. I have changed this snippet into the following using dummyids that have a schema of string:

    const {emailid: emailidParam, password: pwd} = creds;
    let [token, error] = Array(2).fill(null);
    console.log(`<---------  reaching getJwtToken   ----------> 2.2  emailidParam : ${emailidParam}  pwd : ${pwd}`);
    const allUsers = await User.find({});
    console.log('Printing all users currently in DB');
    console.log(allUsers);
    const emailid1 = 'abc@abc.com';
    const emailid2 = 'abc@abc.com';
    const dummyid1 = 'dummyabc@dummyabc.com';
    console.log(`<---------  reaching getJwtToken   ----------> 2.2  emailid1 : ${emailid1}`);
    console.log('Printing emailid\'s value');
    console.log(`emailidParam : ${emailidParam}`);
    const userResUsingEmailidParam = await User.findOne({
        'emailid': emailidParam
    });
    const userResUsingEmailId1 = await User.findOne({
        'emailid': emailid1
    });
    const userResUsingEmailId2 = await User.findOne({
        'emailid': emailid2
    });
    const userResUsingDummyId1 = await Dummy.findOne({
        'dummyid': emailid1
    });
    const userResUsingPassword = await User.findOne({
        'password': '$2b$10$1wIH/e/5fetYwgyKmO5BC.q6KhRzG95G2xajJphuH3ZItQcTbuSmi'
    });

![image](https://user-images.githubusercontent.com/13358855/147385269-9c1db0d3-9986-4aca-a4b3-5783c6b628c9.png)
![image](https://user-images.githubusercontent.com/13358855/147385274-cf602cd5-ac49-40fa-ab84-dcd3818cd3ca.png)
![image](https://user-images.githubusercontent.com/13358855/147385278-40e06e47-de00-4684-8b89-f767e9bfd400.png)
![image](https://user-images.githubusercontent.com/13358855/147385282-1f1ca878-4775-4e88-a1b4-07674e5299c7.png)
![image](https://user-images.githubusercontent.com/13358855/147385285-4001fa5c-449b-48b2-b919-0b7788c1faec.png)

**Comment by 12sam12** [comment]
I actually found this issue itself too weird. So only I got quite confused. I resolved it myself. It was some kindof a typo that I found. So closing it now.
