### ISSUE TITLE
Add an example not using Apollo server

### ISSUE THREAD

**Issue by christopher-caldwell** [Urigo/graphql-scalars#1338]
## Is your feature request related to a problem? Please describe.
I cannot get the scalars to run without using Apollo server. I want to use the vanilla `graphql` core package, as Apollo bloats the Lambda bundle by 1mb.

I have followed the provided steps, but GraphQL just calls `.toString()` on the scalar values rather than running the actual scalar.

## Describe the solution you'd like

A guide on how to use this without the need for Apollo.

## Describe alternatives you've considered

Using Apollo, but as stated, I don't want to. I am running this in Lambda, and adding 1mb to the bundle size just for this is not acceptable for me.

## Additional context

Here is a look at what I have, I do not believe this issue is scoped to Lambda, as this should be functional with the core GraphQL call, unless they aren't supported? 

```ts
import { buildSchema, graphql } from 'graphql'
import { DateResolver, DateTypeDefinition } from 'graphql-scalars'

const schema = `#graphql

  ${DateTypeDefinition}

  type Author {
    id: Int!
    name: String!
    createdAt: Date
  }

  type Query {
    author(id: ID!): Author
  }
`

export const handler = (event) => {
  const { query, variables, operationName } = event.body
  const result = await graphql({
    schema,
    contextValue: {},
    rootValue: {
      Date: DateResolver,
      author: () => {...}
    },
    source: query,
    variableValues: variables,
    operationName,
  })
}
```

`author` works as expected, but the date is just the date with `.toString()` tacked on the end. I can remove the `Date: DateResolver` from the resolvers, and it will function the same way.

**Comment by christopher-caldwell** [comment]
I found [this issue](https://github.com/graphql/graphql-js/issues/497#issuecomment-1001074079) which solved this particular problem. It's not an issue with this library at all, but perhaps an example could still be made. I can do a PR if you'd be open to it.

Closing as this isn't an issue with this library.

**Comment by Urigo** [comment]
@christopher-caldwell we would love to get an example from you!

**Comment by christopher-caldwell** [comment]
@Urigo Great! I'll comment on this when I have a PR
