### ISSUE TITLE
Can't load the package.

### ISSUE THREAD

**Issue by SamMcKay** [Urigo/graphql-scalars#135]
I can't load the package.  I receive the following error using v1.0.3.

const scalars = require('graphql-scalars');

ReferenceError: BigInt is not defined

Works as advertised for v1.0.2

**Comment by ardatan** [comment]
@SamMcKay Could you try with the following canary version?
`1.0.4-dc0dc05.0`
By the way, what version of Node are you using?

**Comment by ardatan** [comment]
Fixed in 1.0.4!
