### ISSUE TITLE
EmailAddress doesnt complain with "email@exemple" 

### ISSUE THREAD

**Issue by AntoineC-dev** [Urigo/graphql-scalars#1462]
**Describe the bug**
The EmailAddress type validates strings like "email@exemple" with no ".com" or whatever

**Expected behavior**
Should return some error when their is not a "." after the "@"

**environement**
Implemented in a nexus/graphql environment like so:

TYPE:
```javascript
import { GraphQLEmailAddress } from "graphql-scalars";
import { asNexusMethod } from "nexus";

export const GQLEmail = asNexusMethod(GraphQLEmailAddress, "email");
```

MUTATION:
```javascript
export const UserMutation = mutationType({
  definition(t) {
    t.nonNull.field("createUser", {
      type: "User",
      args: {
        username: nonNull(stringArg()),
        email: nonNull("EmailAddress"),
        password: nonNull(stringArg()),
      },
      async resolve(_, args, ctx) {
        const { email, password, username } = args;
        const hash = await argon2.hash(password);
        return ctx.prisma.user.create({
          data: {
            email,
            username,
            password: hash,
          },
        });
      },
    });
  },
});
```

- OS: Windows 10
- GraphQL Scalars Version: 1.14.1
- NodeJS: 17.3.0

**Comment by ardatan** [comment]
It is a valid email according to the spec we follow;
https://www.w3.org/Protocols/rfc822/

If this scalar doesn't work for you, you can create your own with `RegularExpression` scalar factory.
