### ISSUE TITLE
UUID scalar accepts uuid value wrapped in `{}`

### ISSUE THREAD

**Issue by ZiiMakc** [Urigo/graphql-scalars#1514]
**Describe the bug**
UUID scalar accepts: `{06236013-70de-7000-a9f7-84a2259e653d}` - uuid wrapped in `{}`. Maybe there a reason for that?

**To Reproduce**
From this [code](https://github.com/Urigo/graphql-scalars/blob/728827f133d6448d6e032231df6db06af8e92414/src/scalars/UUID.ts) we can see that validation function removes `{}`:
```
  if (value.startsWith('{')) {
    value = value.substring(1, value.length - 1);
  }
```

**Expected behavior**
UUID wrapped in `{}` should not be accepted.

**Environment:**
- GraphQL Scalars Version: v1.10.0

**Comment by ardatan** [comment]
Please share  a reproduction on CodeSandbox or StackBlitz. Thanks

**Comment by ZiiMakc** [comment]
@ardatan https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/UUID.ts#L9

**Comment by ardatan** [comment]
https://en.wikipedia.org/wiki/Universally_unique_identifier
Microsoft GUIDs have `{}` so the scalar needs to have `{}` in the regexp to support those. See the article above.
