### ISSUE TITLE
Can't build project, typescript fails, wrongly defined dependencies on ts/graphqljs/other libs?

### ISSUE THREAD

**Issue by tomasstrejcek** [Urigo/graphql-scalars#1522]
There is possibly bug in dependencis if I can install this and then if fails during compilation, right?

v1.14.1 build fine, but i can't seem to find any changelog or something to find out what are the upgrade steps, reasons for BC in minor version etc :(

example errors:
node_modules/graphql-scalars/scalars/AccountNumber.d.ts:3:44 - error TS2315: Type 'GraphQLScalarType' is not generic.

3 export declare const GraphQLAccountNumber: GraphQLScalarType<string, string>;

node_modules/graphql-scalars/scalars/RoutingNumber.d.ts:3:44 - error TS2315: Type 'GraphQLScalarType' is not generic.

3 export declare const GraphQLRoutingNumber: GraphQLScalarType<string, string>;

**Environment:**

- OS: MacOS m1
- GraphQL Scalars Version: v 1.15.0
- NodeJS: 16.7.0
- typescript 4.5.2
- graphql 15.6.1

**Comment by ardatan** [comment]
We don't have any dependency except `tslib`(just a small helper library).
It seems it is just mismatching types for v15. I'll cut a patch release.

**Comment by ardatan** [comment]
Fixed in the latest release. Please let us know if it still fails.
