### ISSUE TITLE
Date validation fails

### ISSUE THREAD

**Issue by dannysofftie** [Urigo/graphql-scalars#1524]
**Describe the bug**
The date validator seems to not accept dates for different locales
```js
// Expected type "Date". Date cannot represent an invalid date-string 3/31/2022
```
**To Reproduce**
Example 1:
```js
const caLocaleDate = new Date().toLocaleDateString('en-CA', { timeZone: 'Africa/Nairobi' })
// returns 2022-03-23 which validates well with graphql-scalars Date object
const enLocaleDate = new Date().toLocaleDateString('en-US', { timeZone: 'Africa/Nairobi' })
// returns 3/23/2022 which fails with error above of invalid date-string
```

**Expected behavior**
Date generated by JavaScript Date object should validate
**Environment:**

- OS: `Ubuntu 20.04`
- GraphQL Scalars Version: `"graphql-scalars": "^1.15.0"`
- NodeJS: `v16.13.2`

**Additional context**
Both `caLocaleDate` and `enLocaleDate` will return expected date values when run with `new Date(value)`. E.g
```js
new Date(caLocaleDate) // 2022-03-23T00:00:00.000Z
new Date(enLocaleDate) // 2022-03-22T21:00:00.000Z
```

**Comment by ardatan** [comment]
It should follow RFC standard as defined in here;
https://www.graphql-scalars.dev/docs/scalars/rfc3339.txt
So the format should be YYYY-MM-DD
