### ISSUE TITLE
[BUG] ReferenceError: URL is not defined with Node v8.16.0

### ISSUE THREAD

**Issue by Ragyal** [Urigo/graphql-scalars#156]
URL is not working with Node 8 with Versions newer than v1.0.1.
Running code with v1.0.4 and Node 8 results in:
```ReferenceError: URL is not defined```

Using Node 12 is possible. Do you deliberately not support Node 8?

**Comment by ardatan** [comment]
Could you try with the following version?
`1.0.5-b0b7e22.0`

**Comment by Ragyal** [comment]
@ardatan Nothing changed. Node 8 is still throwing an error and Node 12 is working fine.

**Comment by ardatan** [comment]
@Ragyal Could you share whole stack trace? Because tests are passing in Node 8.16.0.

**Comment by Ragyal** [comment]
```
(node:24765) UnhandledPromiseRejectionWarning: ReferenceError: URL is not defined
    at /Users/ragyal/projectFolder/src/index.ts:23:19
    at Generator.next (<anonymous>)
    at /Users/ragyal/projectFolder/src/index.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ragyal/projectFolder/src/index.ts:4:12)
    at startServer (/Users/ragyal/projectFolder/src/index.ts:29:12)
    at Object.<anonymous> (/Users/ragyal/projectFolder/src/index.ts:111:1)
    at Module._compile (module.js:653:30)
    at Module.m._compile (/Users/ragyal/projectFolder/node_modules/ts-node/src/index.ts:530:23)
    at Module._extensions..js (module.js:664:10)
(node:24765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ardatan** [comment]
@Ragyal It looks the error has been thrown inside your `index.ts`. Is there any chance to create a reproduction repo to see it better?

**Comment by Ragyal** [comment]
@ardatan i am going to prepare a repo for you when i am back home today

**Comment by Ragyal** [comment]
Ok, it seems like v1.0.1 was hiding another problem in our codebase which has been revealed by v1.0.4.
See https://github.com/Ragyal/graphql-scalars-repro-repo

Using URLResolver with v1.0.1 'saved' us from named ReferenceError, since we used URL without importing it. With v1.0.4 URLResolver has changed and could not fix our mistake anymore. Making our own code not backward compatible for Node v8.

**Comment by ardatan** [comment]
https://github.com/Ragyal/graphql-scalars-repro-repo/blob/b35dd4082127d3c7bce35a72dba4cbd64e2d8dd5/src/index.ts#L23
In here you need to import URL from url package if you want to use it.
Add `import { URL } from 'url';` and it would be fixed. As you can see in the error, the error comes from this line not `graphql-scalars`.
