### ISSUE TITLE
Use with apollo-server-express and CommonJS

### ISSUE THREAD

**Issue by cedric25** [Urigo/graphql-scalars#158]
Not really an issue but simply to show what I had to do to make it work with apollo-server-express and CommonJS imports. (Only Apollo Server and ES6 imports in README so far)

In my `typeDefs` and `resolvers`:
```
const { DateTimeResolver, DateTimeTypeDefinition } = require('graphql-scalars')

const typeDefs = [
  DateTimeTypeDefinition,
]

const resolvers = [
  { DateTime: DateTimeResolver }, // <-- Notable difference here
]
```

Just if someone gets here with the same context... 👍

**Comment by Urigo** [comment]
@cedric25 maybe it's worth create a PR with an example or something that mention it in the README?

**Comment by ardatan** [comment]
Added with PR #192 thanks to @cedric25 :)
