### ISSUE TITLE
Add `"types"` entries to the `"exports"` property of `package.json`, to allow consumption from Typescript with the new `Node16` module resolution strategy

### ISSUE THREAD

**Issue by Duncan3142** [Urigo/graphql-scalars#1602]
**Is your feature request related to a problem? Please describe.**

I'm unable to consume `"graphql-scalars"` from Typescript 4.7, when module resolution is set to `Node16`

**Describe the solution you'd like**

Add `"types"` entries to the `"exports"` property of package.json

**Describe alternatives you've considered**

None

**Additional context**

The following would suffice

```
"exports": {
  ".": {
    "types": "./index.d.ts",
    "require": "./index.js",
    "import": "./index.mjs"
  },
  "./*": {
    types": "./*.d.ts",
    "require": "./*.js",
    "import": "./*.mjs"
   },
  "./package.json": "./package.json"
}
```

**Comment by ardatan** [comment]
Available in the latest release!
