### ISSUE TITLE
Throw a subclass of TypeError

### ISSUE THREAD

**Issue by strongpauly** [Urigo/graphql-scalars#1644]
**Is your feature request related to a problem? Please describe.**

I have a custom error handler that I would like to do something specific when a scalar fails validation.  Currently I have no easy way to tell whether a `TypeError` was generated from scalar validation or from elsewhere in the codebase.

**Describe the solution you'd like**
If this library could throw a subclass of TypeError, or in some other way indicate that the errors thrown were due to validation issues then my custom error handler could safely handle them and ignore others.

**Describe alternatives you've considered**
I could interrogate the messages thrown by this library and filter them via regex, but this seems prone to error and would rely on the messages not changing.

**Additional context**
Using a custom subclass of TypeError would mean that any existing code that checks for `instanceof TypeError` should still work

**Comment by ardatan** [comment]
How do you catch the errors of the default scalars because they don't throw`TypeError`?

**Comment by strongpauly** [comment]
My current logic (which I admit isn't great) is that is there is no original error in the GraphQLError, then it was a validation error thrown from the scalars, or at the very least a client side problem and not a server side one.

**Comment by ardatan** [comment]
@strongpauly So you can do the same with graphql-scalars, right? I think we follow the same pattern of graphql.js as you can see in the link I shared. I don't think it is a good idea to use `TypeError`s which can lead unexpected results when you use this kind of error masking;
https://the-guild.dev/graphql/yoga-server/docs/features/error-masking
