### ISSUE TITLE
NPM <--> GitHub releases different

### ISSUE THREAD

**Issue by bombillazo** [Urigo/graphql-scalars#1649]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the GraphQL Scalars package version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
This repo specifies the latest release is `1.10.0`, yet NPM is already various versions ahead (so far latest is `1.17.0`).

**To Reproduce**

N/A

**Expected behavior**
Github has documentation and releases in sync with NPM

**Environment:**

- OS:
- GraphQL Scalars Version:
- NodeJS:

**Additional context**

**Comment by ardatan** [comment]
Updated! Thanks for reporting this!
