### ISSUE TITLE
[Request] Please add new scalar types

### ISSUE THREAD

**Issue by blacksmoke26** [Urigo/graphql-scalars#165]
I would like to make a request for new types:

1. Date (Date only)
2. Time (Time only)
3. Timestamp (Not required but nice to have)

Thank You!

**Comment by blacksmoke26** [comment]
For more info, Please check the following package:

https://github.com/excitement-engineer/graphql-iso-date

**Comment by ardatan** [comment]
@blacksmoke26 Great idea! PRs are welcome :)

**Comment by konsumer** [comment]
Would it be acceptable to just import graphql-iso-date in this lib and expose it's scalars?

**Comment by ardatan** [comment]
@konsumer If that package is treeshakable, it would be fine.

**Comment by ryanhs** [comment]
@blacksmoke26 I would like to have it too!
Lets discuss about Time,

ISO 8601 have this following format:

- Date and time in UTC
- Week
- Week with weekday
- Date without year
- Ordinal date

Which format can we use for Time?

I think for timestamp, it should be separated between second and milliseconds, example: `Timestamp` and `TimestampMS`

**Comment by blacksmoke26** [comment]
*Date and time in UTC* for sure!

**Comment by blacksmoke26** [comment]
Date => YYYY-MM-DD
Time => HH:MML:SS
Timestamp => YYYY-MM-DD HH:MML:SS

**Comment by ardatan** [comment]
@blacksmoke26 PRs are welcome!

**Comment by ardatan** [comment]
Available in https://github.com/Urigo/graphql-scalars/releases/tag/1.1.6 !
