### ISSUE TITLE
Misunderstanding with Hexadecimal scalar type

### ISSUE THREAD

**Issue by kolegm** [Urigo/graphql-scalars#167]
As expected, [hexadecimal](https://github.com/Urigo/graphql-scalars#hexadecimal) must be able to use.

But, Unknown type "Hexadecimal". It is not exported from the package.

Please, help me to understand is this a bug or was it specifically missed??

**Comment by ardatan** [comment]
Could you share more details like how you import the library and use in your existing project?

**Comment by kolegm** [comment]
Well, I'll try to show my case:

At **typeDefs** used:

`
import` { typeDefs as externalScalars } from 'graphql-scalars';
import types from './types';
import queries from './queries';
import inputs from './inputs';
import mutations from './mutations';

const linkSchema = gql\`
  type Query {
    _: Boolean
  }
  type Mutation {
    _: Boolean
  }
`;

export default [
  linkSchema,
  ...externalScalars,
  ...types,
  ...queries,
  ...inputs,
  ...mutations
];
`

One of **types** is:
`
import { gql } from 'apollo-server-koa';
  
export default gql\`
  type UserToken {
    id: GUID!
    user: User!
    token: String # @TODO: Hexadecimal must be, does not work!
  }
`;

And related resolvers:
`
import { resolvers as externalScalars } from 'graphql-scalars';

import queries from './queries';
import mutations from './mutations';]

export default [externalScalars, queries, mutations];
`

**Comment by ardatan** [comment]
@kolegm That's our bug. `Hexadecimal` type definition is missing. So you can add `scalar Hexadecimal` in your code to make it work until it gets fixed.

**Comment by ardatan** [comment]
Available in 1.0.5!
