### ISSUE TITLE
Value is not a valid Date format (YYYY-MM-DDTHH:MM:SS.SSSZ): 2007-12-03T10:15:30Z

### ISSUE THREAD

**Issue by benliu723** [Urigo/graphql-scalars#169]
From my understanding, 2007-12-03T10:15:30Z is also a datetime format, however, this doesn't allow by using graphql-scalars. 

because,

![image](https://user-images.githubusercontent.com/1772367/70421324-94b3ee00-1aa4-11ea-9b7c-d8a7c6e8524c.png)

Hope this can be solved.

**Comment by ardatan** [comment]
Available in 1.0.5!
