### ISSUE TITLE
JSON and JSONObject have null prototype

### ISSUE THREAD

**Issue by hdaws** [Urigo/graphql-scalars#1696]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the GraphQL Scalars package version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**
GraphQLJSON and GraphQLJSONObject set a null prototype, which breaks interoperability with other frameworks.
If a GraphQLString is passed then JSON parsed, this issue does not occur, I would expect the behavior to be the same. 

**To Reproduce**
Use GraphQLJson or GraphQLJsonObject as an *input* scalar into any mutation. The resultant argument passed to the resolver will have a null prototype

**Expected behavior**
a normal json object with the "Object" prototype should be received as if Json.parse was called on a string. n

**Environment:**

- OS: OSX but all platforms apply
- GraphQL Scalars Version: 1.17.0
- NodeJS: 16.13, 18.x are both reproducible

**Additional context**
In specific, this makes the JSON object a problem to pass to other frameworks or code that anticipate a real object where the spread operator, constructor, etc work as normal. It's not relevant for output really.

**Comment by hdaws** [comment]
I realize this is probably from the fact the graphql-json-type package is adapted here and the original package does this. I'm not sure that package is maintained any longer and feel like this should be fixed in a package that is maintained.

**Comment by hdaws** [comment]
line 19 of https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/json/utils.ts is where this is done, although other types do not appear to use this convention.

**Comment by ardatan** [comment]
Would you create a failing test on the repo or at least a reproduction on CodeSandbox or StackBlitz that shows the problem?

**Comment by ardatan** [comment]
Closing the issue due to the inactivity.
