### ISSUE TITLE
Semantic Versions

### ISSUE THREAD

**Issue by jbendes** [Urigo/graphql-scalars#1701]
Has anyone considered adding a semantic version scalar to this library? Love all the scalar options available and think a semantic version scalar as outlined in https://semver.org/ would be great. It essentially just a string with a specific regex describing its validity. Since it's so simple, it's easy to implement in each project you want to use it in, but since it's so widely used, it'd be pretty convenient to have it in a great library like this one. Let me know your thoughts!

**Comment by mammadataei** [comment]
I'll work on this.
