### ISSUE TITLE
Add IP scalar

### ISSUE THREAD

**Issue by mammadataei** [Urigo/graphql-scalars#1714]
**Problem:** 

As you know, it's not currently possible to union scalars in graphql, so if you have a field which is `IPv4` **or** `IPv6`, you can't use those scalars to describe it.

```graphql
type Network {
  IP: IPv4 | IPv6 # Oops!
}
```

**Solution:**

I think it would be great if there were an `IP` scalar that accepts both `IPv4` and `IPv6`.

```graphql
type Network {
  IP: IP
}
```

And I think it's possible to use existing `IPv4` and `IPv6` scalars functionality for `IP` validation.

**Comment by ardatan** [comment]
PRs are welcome!
