### ISSUE TITLE
Stale bits around EmailAddress

### ISSUE THREAD

**Issue by spencerwilson** [Urigo/graphql-scalars#1791]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the GraphQL Scalars package version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

https://github.com/Urigo/graphql-scalars/commit/06c48c0312077d42b77b2e43b2f7fc0226b8fee4 updated the email regex away from RFC 822, but yet there remain docs that refer to RFC 822: https://github.com/Urigo/graphql-scalars/search?q=rfc822

Those references should probably be updated, too.

**To Reproduce**

**Expected behavior**

**Environment:**

- OS:
- GraphQL Scalars Version:
- NodeJS:

**Additional context**

**Comment by ardatan** [comment]
![image](https://user-images.githubusercontent.com/20847995/215086168-42cdd5d7-a80c-4cbf-952d-5dbd75b9b51e.png)
Can you send the link of the misleading docs? Because I cannot see any in the link you sent.
