### ISSUE TITLE
Add Custom Scalars for Common Library Classification Codes

### ISSUE THREAD

**Issue by cmhhelgeson** [Urigo/graphql-scalars#1816]
As of right now, GraphQL-Scalars does not support common library classification codes such as Dewey, Library of Congress (LCC), or UDC (Universal Decimal Classification), which are common usually at academic institutions in America and across the world. Any library that would want to migrate to using GraphQL in any fashion may benefit from having scalar types that directly correspond to these classifications, or sub-aspects of these classifications. 

For instance, there could easily be a custom scalar for the Dewey decimal system (a simple regex allowing a 1-3 digit whole number followed by an arbitrary number of decimal points), while other classifications (LCC or UDC) are more complex but can be achieved or broken down into equally useful components.

Alternatives could be writing a library that only considers scalars for library classifications, but I feel like the proposed scalars could be suited well within this collection.

*Additional context*
Information about Dewey Decimal Classification: https://www.oclc.org/en/dewey.html#ten
Library of Congress Classification Info: https://www.loc.gov/catdir/cpso/lcco/
Universal Decimal Classification (UDC): https://udcsummary.info/php/index.php

**Comment by ardatan** [comment]
Available in the latest release! Thanks!
https://github.com/Urigo/graphql-scalars/pull/1860
