### ISSUE TITLE
Cannot use NonNegative* types

### ISSUE THREAD

**Issue by heavencyj** [Urigo/graphql-scalars#189]
I couldn't start my server after adding NonNegativeInt. Digged around a bit and found the issue:

https://github.com/Urigo/graphql-scalars/blob/master/src/resolvers/index.ts#L34
Seems like a typo here. Should be "NonNegativeInt".

I am using UnsignedInt but figure I should report this.

**Comment by ardatan** [comment]
Available in 1.0.5 :)
