### ISSUE TITLE
GraphQLScalarType TInternal and TExternal are unknown

### ISSUE THREAD

**Issue by Liam-Tait** [Urigo/graphql-scalars#1919]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the GraphQL Scalars package version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

When using scalar types, `TInternal` and `TExternal` are typed as `unknown`. This is because there is an explicit type added to the scalar's export.

**To Reproduce**

Inspect the type of the scalars looking at `TInternal` and `TExternal`

To extract these we can use the following helper types
```ts
type ExtractTInternal<Type> = Type extends GraphQLScalarType<infer Internal, unknown> ? Internal : never
type ExtractTExternal<Type> = Type extends GraphQLScalarType<unknown, infer External> ? External : never
```

For example
```ts
type DateTimeTInternal = ExtractTInternal<DateTimeResolver> // type of DateTimeTInternal is unknown
type DateTimeTExternal = ExtractTInternal<DateTimeResolver> // type of DateTimeTExternal is unknown
```

**Expected behavior**

I expect the scalars to have the `TInternal` and `TExternal` types match the config.
```ts
type DateTimeTInternal = ExtractTInternal<DateTimeResolver> // type of DateTimeTInternal should be Date
type DateTimeTExternal = ExtractTInternal<DateTimeResolver> // type of DateTimeTExternal should be Date
```

**Environment:**

- OS: 13.3.1
- GraphQL Scalars Version: 1.23.3
- NodeJS: 18.12.1

**Additional context**

There is an alternate apporach to removing the explicit type and that is to add the `TInternal` and `TExternal` types to the explicit type instead. This means the types would get duplicated from the config instead of inferred.

**Comment by ardatan** [comment]
Fixed by your PR!
Thanks!
