### ISSUE TITLE
UnsignedFloat throw error for Int value

### ISSUE THREAD

**Issue by heavencyj** [Urigo/graphql-scalars#194]
I am using UnsignedFloat scalar but it's throwing error when I pass an int value. is that intended? I cannot create my own union input type with both UnsignedInt and UnsignedFloat. And I checked 
https://github.com/graphql/graphql-js/blob/master/src/type/scalars.js#L118 that they validate with both Float and Int when validate for Float.

**Comment by ardatan** [comment]
@heavencyj You might be passing string or something else. Could you share a reproduction repo?

**Comment by heavencyj** [comment]
I am passing in an int. 
https://github.com/Urigo/graphql-scalars/blob/master/src/resolvers/NonNegativeFloat.ts#L22 only checks kind.Float so it will throw error on kind.Int. Whereas the graphql repo checks both type when validating Float. It should be reproducible easily.

**Comment by heavencyj** [comment]
to your point, i did send the param in as a string. but should it error out though? it just seems inconsistent from the `Float` type behavior in graphql.

**Comment by ardatan** [comment]
@heavencyj You're right. I updated the condition in Float types. You can try it with the canary version.
`1.0.6-0fbf191.0`

**Comment by ardatan** [comment]
Fixed in 1.0.6!
