### ISSUE TITLE
BigInt is Breaking

### ISSUE THREAD

**Issue by anshuman61** [Urigo/graphql-scalars#1966]
**Environment:**

- OS: Windows
- GraphQL Scalars Version: 1.22.2
- NodeJS: 16.17.1

**Additional context**

The BigInt type is Breaking with error message "Do not know how to serialize BigInt" (After update ) . It was good upto 1.20.1

**Comment by ardatan** [comment]
Could you share a reproduction?

**Comment by anshuman61** [comment]
![graphql](https://github.com/Urigo/graphql-scalars/assets/64569737/370b927a-a264-4bc5-8b25-4157218849ef)

Well after couple of tries with Code Sand Box i am not able to reproduce the issue... I have a screenshot which describes the same.. I have a prod application... which uses `graphql-scalars` ... but all of sudden after a build it started throwing error as shown in the screenshot.. I investigated throughout but solved just by replacing the `^` for `graphql-scalars` inside package.json... which was previously `^1.20.1`

**Comment by ardatan** [comment]
Sorry but the screenshot is not helpful. We need a clear reproduction to debug the issue.

**Comment by anshuman61** [comment]
Yeah sure. I ll try to reproduce the same. Closing it for the moment.
