### ISSUE TITLE
Integers are not validated when used as input types

### ISSUE THREAD

**Issue by schmod** [Urigo/graphql-scalars#199]
If I use any of the `Integer` scalar types as a part of an input type (ie. `PositiveInteger`), I'm able to pass in floating-point values (such as `5.5`) without encountering an error.  

I believe these two lines may need to be flipped, as `parseInt` is rather permissive with the inputs that it will accept: 
https://github.com/Urigo/graphql-scalars/blob/master/src/resolvers/utilities.ts#L97-L98

For that matter, I don't fully understand why we're using `parseInt` at all here, as it appears that I can also provide numbers wrapped in strings (ie. `"5"`), as the type-checking that normally happens in `parseLiteral` doesn't appear to happen for input objects. 

GraphQL's built-in `Int` type throws errors in any of these scenarios, as it performs type-checking and validation in the `parseValue` function.

**Comment by ardatan** [comment]
@schmod As I see in GraphQLJS implementation, they use `parseInt` before validating the value in `parseLiteral.
https://github.com/graphql/graphql-js/blob/791be1ae07457701818a5c89dca708053224e897/src/type/scalars.js#L77

**Comment by ardatan** [comment]
@schmod `parseInt` is used in `parseLiteral` for input types as I see in GraphQLJS.
https://github.com/graphql/graphql-js/blob/791be1ae07457701818a5c89dca708053224e897/src/type/scalars.js#L77
So values are coerced to integer in that case.
