### ISSUE TITLE
Docs - missing scalars (DateTimeISO, LocalDateTime, probably more)

### ISSUE THREAD

**Issue by grahamb** [Urigo/graphql-scalars#2019]
It looks like at least two scalars have been added, but are missing from the docs:

- [`DateTimeISO`](https://github.com/Urigo/graphql-scalars/pull/1641#issuecomment-1566801844)
- [`LocalDateTime`](https://github.com/Urigo/graphql-scalars/issues/1848#issuecomment-1552714745)

I would bet there are more; I've only found these two as I'm trying to work through an issue regarding date scalars.

**Comment by ardatan** [comment]
- LocalDateTime is available in the website; https://the-guild.dev/graphql/scalars/docs/scalars/local-date-time
- DateTimeISO doesn't have its own page yet but it's mentioned here; 
https://the-guild.dev/graphql/scalars/docs/scalars/date-time#input-coercion

**Comment by grahamb** [comment]
Ah, I missed LocalDateTime because it's listed as "Local Date Time" in the sidebar, and I was Command-F searching for "LocalDateTime". Most of the other entries in the list are the actual scalar names, so this should probably be changed to "LocalDateTime" (DeweyDecimal is another; it's "Dewey Decimal" in the sidebar).

If the docs are to serve as a list of available scalars, then DateTimeISO should have its own entry.

**Comment by Urigo** [comment]
@grahamb would you be willing to send a PR to update the docs?
