### ISSUE TITLE
Support GeoJSON types

### ISSUE THREAD

**Issue by Maxou44** [Urigo/graphql-scalars#2061]
Add scalars for GeoJSON fields to validate and manipulate Geo data fields

**Describe the solution you'd like**
Support all the type related to GeoJSON data like Point, Polygon or MultiPolygon

**Describe alternatives you've considered**
- https://www.npmjs.com/package/graphql-geojson-scalar-types
- https://github.com/ghengeveld/graphql-geojson
- https://dev.to/trackmystories/how-to-geojson-with-apollo-graphql-server-27ij
- https://brygrill.medium.com/creating-a-geojson-featurecollection-type-for-graphql-352591451b4a
- https://gist.github.com/lkleuver/b7f995cff0c0e153544d5203ad4be665

**Additional context**
The GeoJSON format is defined by RFC 7946: https://datatracker.ietf.org/doc/html/rfc7946

**Comment by ardatan** [comment]
Sounds cool! PRs are welcome!
