### ISSUE TITLE
What the scalar type for Array ?

### ISSUE THREAD

**Issue by Gregory-Canonne** [Urigo/graphql-scalars#212]
What the scalar type for Array ?

**Comment by ardatan** [comment]
@Gregory-Canonne Could you give more details? Are you looking for a scalar type for arrays?

**Comment by Gregory-Canonne** [comment]
Yes, for arrays
Thank you

**Comment by ardatan** [comment]
@Gregory-Canonne There is no special scalar for arrays. They are called `list` in GraphQL.
https://graphql.org/learn/schema/#lists-and-non-null
See here for details
