### ISSUE TITLE
Email Regex Doesn't Support RFC 6531

### ISSUE THREAD

**Issue by jpulec** [Urigo/graphql-scalars#223]
The current Regex for Emails doesn't work any email that has a local part above the 7 bit ASCII table, such as accented characters and Unicode. [RCF 6531](https://tools.ietf.org/html/rfc6531) provides a standard for handling these email addresses.

**Comment by ardatan** [comment]
@jpulec Our Email Address scalar follows W3 standards;
https://github.com/Urigo/graphql-scalars/blob/dcfdeaf1247d30091360b392544252bdd8740084/src/resolvers/EmailAddress.ts#L15

If you want to implement one more specialized, you can use `RegularExpression` factory for your custom scalars.
