### ISSUE TITLE
Example for Apollo Federation

### ISSUE THREAD

**Issue by aimproxy** [Urigo/graphql-scalars#232]
Hi, Im new to Apollo, and in my Accounts Service I use Apollo Federation, the thing is typeDefs in buildFederatedSchema expects a DocumentNode and makeExecutableSchema expects a GraphQLSchema, so thats invalidate the provided example. So, anyone can provide an example for this?

**Comment by ardatan** [comment]
`typeDefs` in `buildFederatedSchema` and `typeDefs` in `makeExecutableSchema` are similar. I don't think we need any specific example for Apollo Federation.
```
import * as graphqlScalars from 'graphql-scalars';

buildFederatedSchema({
        typeDefs: gql`
             # Your TypeDefs here
             ${graphqlScalars.typeDefs.join('\n')}
         `,
         resolvers: {
               ...yourResolvers,
               ...graphqlScalars.resolvers,
         }
})
```
