### ISSUE TITLE
[Feature Request] Add file/binary scalar type

### ISSUE THREAD

**Issue by annymosse** [Urigo/graphql-scalars#248]
hopefully there's an ability to add File or Binary scalar

**Comment by ardatan** [comment]
PRs are welcome!

**Comment by ryanhs** [comment]
@annymosse would you describe more about this File / Binary type?

**Comment by annymosse** [comment]
> @annymosse would you describe more about this File / Binary type?

sorry i took a long time since i accessed my Github account (i have migrated since it acquired by MS evils), for this feature we had an experiment inside the company where i was working in by using GraphQl as FTP uploading/downloading files using GQL instead RESTful API and not using static file servers such as NGINX ,later on we had realized GQL it's not performed for binary files, so we end up making similar solution but it's not Gql using rust and cpp.

**Comment by annymosse** [comment]
> Actually, does GraphQL support receiving binary data from client? Or it has to be a base64 string?

@dzcpy you're right if it will replay with base64 we need to set it as `String` type, and No GraphQL not supposed to recieve binaries ,but my case request this feature.
