### ISSUE TITLE
BigInt not serializing

### ISSUE THREAD

**Issue by ncioj10** [Urigo/graphql-scalars#253]
Hi,
unfortunately the BigInt does not seem to work at the moment.
With Node v12.16.1 I get the error.
`"TypeError: Do not know how to serialize a BigInt",
              "    at JSON.stringify (<anonymous>)",
              "    at prettyJSONStringify (/node_modules/apollo-server-core/src/runHttpQuery.ts:457:15)",
              "    at /node_modules/apollo-server-core/src/runHttpQuery.ts:330:16",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/node_modules/apollo-server-core/dist/runHttpQuery.js:5:58)",
              "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"`
I managed to fix it with: (BigInt as any).prototype.toJSON = function() { return this.toString(); };
But that sort of defeats the whole process as now I am only sending it as string, which would've been possible before.

Best,
Nicolas

**Comment by ardatan** [comment]
Fixed in 1.0.8!
