### ISSUE TITLE
IBAN validation ignores non alphanumeric characters

### ISSUE THREAD

**Issue by antogyn** [Urigo/graphql-scalars#283]
Hey,

Because of this code:

https://github.com/Urigo/graphql-scalars/blob/fb7cb490cd789d3923902e2362aabd816dd73ff7/src/resolvers/IBAN.ts#L207-L209

Non alphanumeric characters aren't validated, e.g. IBANs like `AL35  202$,;?111090000000001234567` pass validation and are returned as is.

I'd be ok to send a PR, but a fix would be a breaking change, so ignoring alphanumeric characters should probably stay the default behaviour. Any suggestion ?

**Comment by Urigo** [comment]
thank you @antogyn 
We would love to get a PR that validates it.

If it's a broken behavior, fixing it doesn't consider a breaking change in terms of semver in my opinion..

**Comment by ardatan** [comment]
Available in v1.1.3
