### ISSUE TITLE
GUID Scalar regex doesnt work properly

### ISSUE THREAD

**Issue by 3logy** [Urigo/graphql-scalars#310]
I have a valid GUID: 38336562-3634-6431-2d39-3264302d3400 (tested on http://guid.us/Test/GUID)

when i try to send this query with accountId define as a scalar GUID
`query {
  account(accountId: "38336562-3634-6431-2d39-3264302d3400") { 
  	email
  }
}`

I have a the following error : **Value is not a valid GUID**

**Comment by ardatan** [comment]
Could you try with the following canary version?
`1.1.3-060e256.0`
