### ISSUE TITLE
ISBN resolver shouldn't require "ISBN" prefix

### ISSUE THREAD

**Issue by sambowler** [Urigo/graphql-scalars#347]
Hi,

Thanks for providing such a useful library. I've been looking at implementing the ISBN resolver which appears to require the string be prefixed with `ISBN` e.g. `ISBN 978-0-12-345678-9`. From reading through the [ISBN guidelines on isbn-international.org](https://www.isbn-international.org/content/what-isbn) and on [Wikipedia](https://en.wikipedia.org/wiki/International_Standard_Book_Number) it doesn't look like this should be required i.e. `978-0-12-345678-9` should also be acceptable?

Thanks!

**Comment by ardatan** [comment]
PRs are welcome to update the regex.

**Comment by ryanhs** [comment]
@sambowler I created PR for this fix :) turns out the grouping in regex the problem

**Comment by sambowler** [comment]
@ryanhs You beat me to it! Thank you!

**Comment by ardatan** [comment]
Let's keep it open until it gets released!
