### ISSUE TITLE
[Bug] TS2304: Cannot find name 'URL' when building TS Project using tsc command

### ISSUE THREAD

**Issue by kanstantsin-chernik** [Urigo/graphql-scalars#348]
I don't think addin `DOM` is an option. I don't use it, why would I add it.

**Comment by kanstantsin-chernik** [comment]
Related to #342 which is closed for some reason

**Comment by kanstantsin-chernik** [comment]
I think the mock should be:
`declare const URLMock: () => import('url').URL;`

**Comment by ardatan** [comment]
`url` module is Node-specific, browser doesn't have it. You still need an extra package for your solution which is `@types/node`

**Comment by ardatan** [comment]
Fixed in 1.1.5!

**Comment by kanstantsin-chernik** [comment]
Thank you!

**Comment by cerino-ligutom** [comment]
Needed a quick workaround for #342 so adding `DOM` sufficed back then for testing though we ended up using `patch-package` to patch the lib when we deployed to prod. But since this finally got solved without us users adding `DOM` now, great! Thank you!
