### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by pauldowman** [Urigo/graphql-scalars#37]
We're not able to maintain this any more. If you would like to maintain it please let me know.  But I don't want to just transfer it to someone random, to avoid another [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident) (not that this package is anywhere near as widely used). 

If you have been contributing to this package or have other good contributions to show I'll be happy to recommend your fork.

**Comment by wlaaraki** [comment]
I would like to continue maintaining this package, we are using it in our e-commerce website

**Comment by pauldowman** [comment]
Great, thanks @wlaaraki. I think you should fork it, and I will update the README to point to your fork.

**Comment by Urigo** [comment]
Hi Everyone!

Thanks to the great leadership of @pauldowman , we've had a conversation and The Guild would take the work of maintaining of `merge-graphql-schemas` and `graphql-scalars`.

We will release a blog post soon with more details and a roadmap.

All the great words of appreciation I have to say to @pauldowman and the amazing team from ok-grow will be written in the blog post and referenced here.

**Comment by Urigo** [comment]
@wlaaraki please reach out to me directly so we can have your changes released and merged even before we'll release the roadmap (my email is public on my Github profile)
