### ISSUE TITLE
Wrong regex for EmailAddress type definition

### ISSUE THREAD

**Issue by miguelcaro** [Urigo/graphql-scalars#371]
const EMAIL_ADDRESS_REGEX = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;

this regex allows formats like **_test@testing_** also **_1222@122.1111_** and these formats are incorrect

**Comment by ardatan** [comment]
@miguelcaro That regex comforts W3 specification so W3 supports those email addresses.
