### ISSUE TITLE
Using default valuefor "*Int" scalars

### ISSUE THREAD

**Issue by Borales** [Urigo/graphql-scalars#373]
When assigning a default value for `PositiveInt` (probably for other `*Positive/Negative*` scalars too) type - the generated "graphql docs" tab in GraphQL Playground looks odd.

Same GQL schema:

```gql
type Query {
  hello(page: PositiveInt = 10, pageInt: Int = 10): String
}
```

The generated GraphQL Playground page:

<img width="355" alt="Screenshot 2020-06-14 at 19 49 08" src="https://user-images.githubusercontent.com/1118933/84600224-1f244280-ae78-11ea-8a55-dc4750f0cb7a.png">

https://codesandbox.io/s/graphql-scalar-docs-8xysw?file=/index.js:213-292

**Comment by ardatan** [comment]
It doesn't look like related to graphql scalars. You can create an issue on graphql playground.
