### ISSUE TITLE
[Feature request] Add type Currency

### ISSUE THREAD

**Issue by svengau** [Urigo/graphql-scalars#374]
Hi, 
I've just added the type Currency in [mongoose-schema-types](https://github.com/svengau/mongoose-schema-types/commit/a45db1c832b891fc0b6ff66b77a91fb8a4b43cda). 

It's based on [ISO-4217](https://en.wikipedia.org/wiki/ISO_4217), and it would be great to add it too in graphQL scalars.

I can propose a PR if you're ok.

**Comment by ardatan** [comment]
@svengau Sounds great!

**Comment by svengau** [comment]
@ardatan here it is https://github.com/Urigo/graphql-scalars/pull/375

**Comment by ardatan** [comment]
Available in https://github.com/Urigo/graphql-scalars/releases/tag/1.1.6 !
