### ISSUE TITLE
EmailAddress does not work for nullable fields. 

### ISSUE THREAD

**Issue by schrapel** [Urigo/graphql-scalars#38]
I get the error when my gql is `emailAddress: EmailAddress` without the `!` but surely it should ignore it but instead I get the error `Value is not a valid email address: `

**Comment by ardatan** [comment]
If you don't use `!`, it means it can be `undefined` or `null`. But it must be a valid e-mail address if it is defined.

**Comment by schrapel** [comment]
Null still returns an error saying it’s an invalid email address.
