### ISSUE TITLE
ISO Date SDL Examples are not documented, are breaking change

### ISSUE THREAD

**Issue by rrrix** [Urigo/graphql-scalars#382]
A few minutes ago, I just did a fresh `yarn install` and all of a sudden my GraphQL Server wouldn't start:

```
Error creating Apollo Server:
Error: "Date" defined in resolvers, but not in schema
```

I came here and saw there was a PR that was recently merged: 

[Introduce new ISO Date scalars #380](#380)

1) This is a breaking change if people are importing the scalars provided by this package like this (e.g. using the default export from `graphql-scalars`, like you have [in the Apollo Server example](https://github.com/Urigo/graphql-scalars/blob/master/README.md#usage-with-apollo-server)):

```typescript
import { resolvers as scalars } from 'graphql-scalars';
```

If these 3 new types are missing from the schema SDL, then 💥: 

```graphql
scalar Date
scalar Time
scalar Timestamp
```

2) I would recommend at least putting these three new scalars in the [Usage section in the README](https://github.com/Urigo/graphql-scalars/blob/master/README.md#usage), even though they are in the "Types" section several screens down, so the next person that comes along with this problem can see the changes easily.

Thanks for the new cool ISO Date/Time scalars! 😎

**Comment by ryanhs** [comment]
`Error: "Date" defined in resolvers, but not in schema`

May we know how the schema added the scalars?

simplest way sometimes i use:
```
${Object.keys(scalars).map((scalar) => `  scalar ${scalar}`) .join('\n')}
```

**Comment by ardatan** [comment]
Maybe I am missing something here. 
If you use `typeDefs` and `resolvers` together, you won't get this error. That's why, we export `typeDefs`, too.
If you use some of type definitions together with resolvers of those, you won't get this error again.
