### ISSUE TITLE
DateTime breaking changes for timestamp with milliseconds

### ISSUE THREAD

**Issue by ryanhs** [Urigo/graphql-scalars#387]
DateTime in before version 1.1.6 accept timestamp with milliseconds as `new Date().getTime()`

*new version * throw error `'DateTime cannot represent an invalid Unix timestamp ' + value`
since https://github.com/Urigo/graphql-scalars/blob/100812a339a53d008c9fd7c54f53ff9bd37cae46/src/resolvers/iso-date/validator.ts#L146 guard it for timestamp in seconds only.

I just want to confirm, will we have this behaviour from now on? or is it a bug?

if we stick to timestamp with milliseconds, i'll gladly make a PR for patch

**Comment by lynxtaa** [comment]
Have similar problem: `DateTime cannot represent an invalid date-time-string 2019-01-01T00:00:00`

**Comment by lynxtaa** [comment]
https://github.com/Urigo/graphql-scalars/pull/380 should be breaking change

**Comment by ryanhs** [comment]
@lynxtaa i see, we used to treat the DateTime, as "ISO String" for outside world (graphql schema and client). and use any value that can be put in `new Date(...)` for inside world (our system)

**Comment by ardatan** [comment]
@ryanhs You're right. We should stick with milliseconds.
But @lynxtaa has a different problem. I am not sure if we should support a date string that is invalid against ISO Date standard.

**Comment by ryanhs** [comment]
@ardatan thank you very much bro :+1:
