### ISSUE TITLE
URL Scalar seems to add extra qoutes to the given string

### ISSUE THREAD

**Issue by mondxp** [Urigo/graphql-scalars#416]
Using the URL scalar as an input seems to add quotes at the start and end of the string.
E.g.: serialize function receives the value: _"https://domain.com/test"_ although _https://domain.com/test_ was sent.

This leads to an thrown Error that the url is invalid.

Is it a bug or am I doing something wrong?

**Comment by ardatan** [comment]
Could you create a reproduction on CodeSandbox?

**Comment by mondxp** [comment]
Sorry, thats on me! I overlooked that I am getting a URL object and my db client did save it that way. So everytime I tried to access it threw me an error.
