### ISSUE TITLE
Non-fully qualified URLs

### ISSUE THREAD

**Issue by OliverCole** [Urigo/graphql-scalars#42]
The current regex for URLs excludes examples without fully qualified hostnames - such as `http://server/dir`.

The regex author agreed in the gist, and in [the comments](https://gist.github.com/dperini/729294#gistcomment-2902311) that they are valid,  but that the code met the requirements (for a URL shortener).

Are we open to fixing this?

**Comment by ardatan** [comment]
Are you sure if this kind of URL pattern violates this;
https://www.ietf.org/rfc/rfc3986.txt

**Comment by OliverCole** [comment]
Are you asking whether `http://server/dir` meets RFC 3986? I think it does.

Page 20 says: `reg-name    = *( unreserved / pct-encoded / sub-delims )`

Or are you saying that the regex we have excludes valid RFC 3986 URIs? In which case I agree.

**Comment by ardatan** [comment]
@OliverCole Could you modify regex and submit a PR for this issue?

**Comment by ardatan** [comment]
Fixed in 0.6.7!
