### ISSUE TITLE
Time scalar validation is too strict

### ISSUE THREAD

**Issue by robross0606** [Urigo/graphql-scalars#469]
The regex used to validate ISO8601 times is more strict than the general standard.  For example, the timezone offset is supposed to be optional.  You also do not allow specification of hours without minutes or minutes without seconds.  It also does not allow lower case "z" or "t" as per the RFC 3339 spec..

**Comment by ardatan** [comment]
I think RFC 3339 doesn't allow lowercase, does it?

**Comment by robross0606** [comment]
https://tools.ietf.org/html/rfc3339#page-10

>       NOTE: Per [ABNF] and ISO8601, the "T" and "Z" characters in this
>       syntax may alternatively be lower case "t" or "z" respectively.

**Comment by ardatan** [comment]
Fixed in the latest version!
