### ISSUE TITLE
Scalars are using type coercion

### ISSUE THREAD

**Issue by robross0606** [Urigo/graphql-scalars#479]
Your documentation should make it clearer that you're doing type coercion.  So, for example, submitting "3.1415" will not fail when using `PositiveIntResolver` because ultimately it is being passed through `parseInt()` which will happily convert it to 3.

I would say your documentation is misleading:

> Run-time type checking. GraphQL helps to tighten up the contract between client and server. It does this with strong typing of the interface (or schema). This helps us have greater confidence about what we're receiving from the server and what the server is receiving from the client.

It isn't doing "strong typing" at all. It is doing JavaScript type coercion which is anything but strong.

**Comment by andreialecu** [comment]
New user here. 

Is this true?

Based on the code below, it should validate that a GraphQL `INT` was received prior to parsing it:

https://github.com/Urigo/graphql-scalars/blob/3931faef9f12d2678d70acf3ae80b77613fc0475/src/scalars/PositiveInt.ts#L18-L22

**Comment by ardatan** [comment]
@robross0606 Feel free to create a new issue with a failing test if you still think this doesn't work as expected.

**Comment by robross0606** [comment]
@ardatan Was something changed/fixed or is the code still doing type coercion?

**Comment by ardatan** [comment]
@robross0606 I think same with @andreialecu . Our validators here validate strictly but doesn't do any coercion. If you still think, please create a failing test or a reproduction.

**Comment by robross0606** [comment]
@ardatan Okay, I'll give it a shot as soon as I have time.  Thanks!
