### ISSUE TITLE
Email address validation is wrong. sr@sr "without .com" is coming as valid email.

### ISSUE THREAD

**Issue by ksreejithnair** [Urigo/graphql-scalars#482]
I came to know that we are following RFC822 but RFC 822 was obsoleted in 2001 by RFC 2822, which in turn was obsoleted in 2008 by RFC 5322. The status of RFCs can be checked from the RFC Editor’s RFC database. My fix is not based on latest spec, but what we have in the package is terribly wrong. ard@ard is not a valid email. Let's fix the regex and then update to latest.

This is the pull request
https://github.com/Urigo/graphql-scalars/pull/472

**Comment by ardatan** [comment]
See https://github.com/Urigo/graphql-scalars/pull/472#issuecomment-688295484

**Comment by ksreejithnair** [comment]
Please see comment https://github.com/Urigo/graphql-scalars/pull/472#issuecomment-707453870 and help re opening this.
