### ISSUE TITLE
ISO 8601 duration format

### ISSUE THREAD

**Issue by vespertilian** [Urigo/graphql-scalars#503]
Hi,

Would you be open to a PR with the [ISO 8601 duration](https://www.digi.com/resources/documentation/digidocs/90001437-13/reference/r_iso_8601_duration_format.htm). I am using the dateFns library and it [supports this string format](https://date-fns.org/v2.15.0/docs/formatISODuration). So it might be useful for others.

Side note: the links in your contribution doc are not working. I think you are just missing /docs in the link, must have been moved.

**Comment by ardatan** [comment]
Hi, We'd love to accept a PR!

**Comment by ardatan** [comment]
Available since 1.3.0! Thank you @vespertilian !

**Comment by AdrienLemaire** [comment]
The doc is mentioning the scalar `Duration` and resolver `DurationResolver`, but the actual names are `ISO8601Duration` and `ISO8601DurationResolver`.
Would be nice to have an alias, or fix the readme doc.
