### ISSUE TITLE
Rename GUID to UUID or create an alias

### ISSUE THREAD

**Issue by carlocorradini** [Urigo/graphql-scalars#517]
**Can we rename GUID to UUID?**
From wikipedia: "A universally unique identifier (UUID) is a 128-bit number used to identify information in computer systems. The term globally unique identifier (GUID) is also used, typically in software created by Microsoft."
Since UUID is more "_universal_" and expressive (Databases, Type, etc..) rather than GUID that refers to Microsoft specific products.
Can this be done?
Another solution is to create an alias such as the example _NonNegativeInt_ and _UnsignedInt_.

**Comment by ardatan** [comment]
That sounds good! Would you care to try a PR for this?

**Comment by carlocorradini** [comment]
See https://github.com/Urigo/graphql-scalars/pull/518.

**Comment by ardatan** [comment]
Available in 1.4.0! Thanks @carlocorradini
