### ISSUE TITLE
Add 24 hour (unqualified local time). 

### ISSUE THREAD

**Issue by vespertilian** [Urigo/graphql-scalars#531]
I commented on #480 but I figure this might be worth its own issue number. 

I am keen on adding a 24 hour time scalar to this library without offsets or UTC designators. My issue with the current time implementation is that forces a timezone either 'Z' (UTC) or the offset. What I am capturing in my app is the 24-hour time string without an offset, as the user is entering it irrespective of timezone.

Reading through rfc3339, they seem to refer to this time as unqualified local time. 

I kinda liked `24hourTime` but I don't think we can start the scalars with numbers so it would be `twentyFourHourTime` .... which is very long. 

Maybe `ULTime` would be a nice short scalar label for this? 

Let me know if you're happy for me to add it?

**Comment by ardatan** [comment]
Available in v1.5.0!
