### ISSUE TITLE
EmailAddress doesn't support diacritics characters

### ISSUE THREAD

**Issue by Shahor** [Urigo/graphql-scalars#574]
`EmailAddress` scalar is missing some validations around diacritics, as per RFC 

- https://en.wikipedia.org/wiki/Email_address#Internationalization_examples
- https://stackoverflow.com/questions/760150/can-an-email-address-contain-international-non-english-characters/31066998#31066998

Is this intentional to keep the validator simple? Or can we build on this?

**Comment by ardatan** [comment]
https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/EmailAddress.ts#L19
We try to follow HTTP spec. But if you have different use cases, you can build your own scalar with a custom regexp;
https://the-guild.dev/graphql/scalars/docs/scalars/regular-expression
