### ISSUE TITLE
Typescript definition for parseLiteral requires 2 arguments

### ISSUE THREAD

**Issue by cyberwombat** [Urigo/graphql-scalars#576]
I am not sure where the issue lies here but thought I'd ask. 

I am using some scalars such as `TimeResolver` and when calling `parseLiteral` such as: `TimeResolver.parseLiteral(value)` Typescript yields an error:
```
(property) GraphQLScalarType.parseLiteral: (valueNode: ValueNode, variables: Maybe<{
    [key: string]: any;
}>) => any
Expected 2 arguments, but got 1.ts(2554)
definition.d.ts(343, 3): An argument for 'variables' was not provided.
```
The definition from the `graphql` package which is where TS seems to pull it from is:
```
export type GraphQLScalarLiteralParser<TInternal> = (
  valueNode: ValueNode,
  variables: Maybe<{ [key: string]: any }>,
) => Maybe<TInternal>;
```
Can someone provide some help on how I should deal with this error?

**Comment by ardatan** [comment]
Sorry for late response but this is not related to this library. What I recommend is to pass an empty object in the second parameter.
