### ISSUE TITLE
How to use the library with TypeGraphQL buildSchema method?

### ISSUE THREAD

**Issue by DarkLite1** [Urigo/graphql-scalars#607]
I couldn't find a help channel for noobs that's why I post my question here. Sorry if this is the wrong place to ask.

We are using [type-graphql](https://typegraphql.com/docs/scalars.html) together with Apollo Server. When following the [documentation](https://github.com/Urigo/graphql-scalars#usage-with-apollo-server) on setting up `graphql-scalars` with Apollo-Server we struggle to get it right. we don't use `makeExecutableSchema` but rather have our code like this:

```typescript
import { ApolloServer, AuthenticationError } from 'apollo-server-express'
import { buildSchema } from 'type-graphql'
import { RosterResolver } from '@sap-truck-roster/resolver/RosterResolver'
import { Roster } from '@sap-truck-roster/entity/Roster'
import { resolvers, typeDefs } from 'graphql-scalars'
import { DateTimeResolver, DateTimeTypeDefinition } from 'graphql-scalars'

export const getSchema = async () => {
  return await buildSchema({
    validate: true,
    resolvers: [
     // resolvers, > Fails
      RosterResolver,
     //   DateTimeResolver, > Fails
    ],
  })
}

export const getApolloServer = async () => {
  return new ApolloServer({
    schema: await getSchema(),
    context,
    dataSources: () => {
      return {
        sapRosterApi: new Roster(),
      }
    },
  })
}
```

We use the UTC date format and `type-graphql` only supports the ISO format, that's why we would like to use your library. It seems like `resolvers` of the method `buildSchema` only accepts an array of classes or glob paths. 

> src/utils/apollo.ts:25:7 - error TS2322: Type '{ Date: GraphQLScalarType; Time: GraphQLScalarType; DateTime: GraphQLScalarType; Timestamp: GraphQLScalarType; ... 43 more ...; Void: GraphQLScalarType; }' is not assignable to type 'string | Function'.

**Comment by ardatan** [comment]
`graphql-scalars` exposes `GraphQLScalarType` objects created with vanilla `graphql-js` but TypeGraphQL uses a decorated classes as `resolvers`. `Resolver` of `graphql-scalars` is compatible with `graphql-tools` resolvers approach.
You can use `GraphQLDateTime` directly as custom scalar as described in TypeGraphQL docs;
https://typegraphql.com/docs/scalars.html#custom-scalars

**Comment by DarkLite1** [comment]
Thank you for the help, much appreciated. I think I still must be doing something wrong...

```typescript
// src\shared\graphql-custom-scalar.ts
import { GraphQLScalarType, Kind } from 'graphql'
import { GraphQLDateTime } from 'graphql-scalars'

export const GraphQLDateTimeScalar = new GraphQLScalarType({
  name: 'GraphQLDateTime',
  description: 'Mongo object id scalar type',
  serialize(value: unknown): string {
    if (!(value instanceof GraphQLDateTime)) {
      throw new Error(
        'GraphQLDateTimeScalar can only serialize GraphQLDateTime values'
      )
    }
    return value.toHexString() // value sent to the client
  },
  parseValue(value: unknown): GraphQLDateTime {
    if (typeof value !== 'string') {
      throw new Error('GraphQLDateTimeScalar can only parse string values')
    }
    return new GraphQLDateTime(value) // value from the client input variables
  },
  parseLiteral(ast): GraphQLDateTime {
    if (ast.kind !== Kind.STRING) {
      throw new Error('GraphQLDateTimeScalar can only parse string values')
    }
    return new GraphQLDateTime(ast.value) // value from the client query
  },
})
```
![image](https://user-images.githubusercontent.com/10828570/100211991-1c407a00-2f0d-11eb-9465-256ca9b0ebfb.png)

Digging deeper

**Comment by ardatan** [comment]
GraphQLDateTime is already a scalar. You don't need to create another one. Just use it :)

**Comment by DarkLite1** [comment]
Yes indeed, that seems to do be the way, thank you. However, now I get conflicts with the built-in `DateTime` scalar and the one from the `grapqhl-scalars` package. Even when trying to destructure it with another name:

```typescript
// entity roster.ts
import { GraphQLDateTime as GraphQLDateTimeScalar  } from 'graphql-scalars'
@ObjectType()
export class Roster extends RESTDataSource {

  @Field(() => GraphQLDateTimeScalar)
  readonly startPlantLoadingDateTime: string
```

**Comment by DarkLite1** [comment]
I think I found a way:

```typescript
import { GraphQLScalarType } from 'graphql'
import { GraphQLDateTime } from 'graphql-scalars'

export const DateTimeUTC = new GraphQLScalarType({
  ...GraphQLDateTime.toConfig(),
  name: 'DateTimeUTC',
})
```

Then use it like this:
```typescript
  @Field(() => DateTimeUTC)
  readonly myDateTime: string
```

**Comment by ardatan** [comment]
@DarkLite1 Using `Date` instead of `string` might work better.
