### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by lookfirst** [Urigo/graphql-scalars#61]
I'm working with Firestore which has a Timestamp class. I ended up using that instead of putting Date.toISOString() everywhere.

Not sure if you want to add dependencies on outside projects so I'm doing this as an issue first vs. a PR ... here is my code...

```
import {Kind} from 'graphql/language';
import {GraphQLScalarType} from 'graphql';
import * as admin from "firebase-admin";
import Timestamp = admin.firestore.Timestamp;

export const TimestampScalar = new GraphQLScalarType({
	name: 'Timestamp',
	serialize(date: Timestamp) {
		return date.toDate().toJSON();
	},
	parseValue(value) {
		const date = new Date(value);
		// eslint-disable-next-line no-restricted-globals
		if (Number.isNaN(date.getTime())) {
			throw new TypeError(`Value is not a valid Date: ${JSON.stringify(value)}`);
		}
		return Timestamp.fromDate(date);
	},
	parseLiteral(ast) {
		if (ast.kind === Kind.INT) {
			return Timestmap.fromDate(new Date(parseInt(ast.value, 10)));
		} else if (ast.kind === Kind.STRING) {
			if (this.parseValue)
				return this.parseValue(ast.value);
		}
		return null;
	},
});
```

**Comment by ardatan** [comment]
We already have `DateTime` which applies most cases for timestamps, and `DateTime` accepts native `Date` instance, numbers and strings in a proper format. This looks `firebase`-specific in my opinion. What do you think? @Urigo

**Comment by lookfirst** [comment]
It *is* firebase specific.

**Comment by ardatan** [comment]
@lookfirst So `graphql-scalars` is a package that includes more generic scalars. It would be better to have this scalar implementation in another npm package under your name in my opinion.

**Comment by Urigo** [comment]
I mean, we can add a firebase-timestamp here if you think it would be valuable for more people

**Comment by lookfirst** [comment]
Thanks @Urigo, don't worry about it. I was just seeing if you were interested. It is fine if not. I actually thought more about things and decided to store Date.toISOString() as a string in Firestore anyway. It just simplifies things.

**Comment by moritzjacobs** [comment]
Thank you, @lookfirst – you just saved me tons of time!

**Comment by cobraz** [comment]
Hello! I've made a separate package to handle this. It's based on graphql-scalars, so it would be easy to import into this package if it every felt right. Meanwhile, people can use this. https://github.com/cobraz/firestore-graphql-scalars
