### ISSUE TITLE
URL scalar is not working in 0.4.7

### ISSUE THREAD

**Issue by jfcieslak** [Urigo/graphql-scalars#62]
**steps to reproduce:**
use URL scalar in Schema, such as: 
```graphql
type Project {
    link: URL
}
```
Define scalar:
```graphql
scalar URL
```

Define resolvers:
```javascript
import { URL, EmailAddress, DateTime } from 'graphql-scalars';

export default {
  EmailAddress,
  URL,
  DateTime,
  // etc.
}
```

**Only when making graphql query** that includes the field with type `URL`, I get the error response inside the graphql tracing:

```
"ReferenceError: URL is not defined"
"at GraphQLScalarType.serialize (<PROJECT>/node_modules/graphql-scalars/dist/commonjs/URL.js:13:9)"
```

- All is fine when queries do not include fields of type `URL`
- All other scalars from this package work just fine (`EmailAddress`, `DateTime`, etc.)

**Comment by ardatan** [comment]
`URL` should be globally defined but I added `URL` from `url` module just in case.

**Comment by jfcieslak** [comment]
> maybe it is related to NodeJS version; because you can see it's working in tests.
Maybe; I am using this scalar in a Firebase Function project, and it runs on node 8. Interestingly, my own tests on that project are passing. So jest running its own test server have no issue with it.

**Comment by ardatan** [comment]
I think Node 8 doesn't have global `URL`, but this case will be supported now in the next release.

**Comment by ardatan** [comment]
Available in 1.0.0!

**Comment by jfcieslak** [comment]
So the issue still persists, this time with typescript declaration:
```
node_modules/graphql-scalars/dist/esnext/mocks.d.ts:14:30 - error TS2304: Cannot find name 'URL'.

14 declare const URLMock: () => URL;
                                ~~~
```
Importing module in mocks.d.ts seems to fix it:
```
import {URL} from 'url';
```

**Comment by ardatan** [comment]
@jfcieslak Could you add `dom` to `lib` field in `tsconfig.json`? Because `URL` is in `global` of NodeJS like browser.
```
    "lib": ["esnext", "dom"],
```

**Comment by jfcieslak** [comment]
> @jfcieslak Could you add `dom` to `lib` field in `tsconfig.json`? Because `URL` is in `global` of NodeJS like browser.
> 
> ```
>     "lib": ["esnext", "dom"],
> ```

That did the trick, thanks!
