### ISSUE TITLE
BigInt / SafeInt confusion

### ISSUE THREAD

**Issue by maxaggedon** [Urigo/graphql-scalars#620]
Just discovered this package as I am looking to fix an issue with `GraphQLInt` and large integers.

I was confused because you say your `BigInt` scalar is based on `graphql-bigint`, and for what I see there (https://github.com/stems/graphql-bigint/blob/master/index.js), that package looks more like your `SafeInt` type...

In the end I think your README explains well what is in this package, but there should not be any mention of `graphql-bigint` in the `BigInt` section as anyone switching from there would get confused as well. I guess the implementation must have evolved and don't reflect the same behaviour anymore.

**Comment by ardatan** [comment]
You're right! I fixed the confusion in README! Thanks!
