### ISSUE TITLE
tslint error

### ISSUE THREAD

**Issue by lookfirst** [Urigo/graphql-scalars#65]
Latest version...

```
node_modules/graphql-scalars/dist/esnext/resolvers/index.d.ts:27:70 - error TS7016: Could not find a declaration file for module 'graphql-type-json'. '/node_modules/graphql-type-json/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/graphql-type-json` if it exists or add a new declaration (.d.ts) file containing `declare module 'graphql-type-json';`

27 import { GraphQLJSON as JSON, GraphQLJSONObject as JSONObject } from 'graphql-type-json';
```

**Comment by ardatan** [comment]
Could you try with the following canary version?
```
1.0.1-7c4ff75.0 
```

**Comment by lookfirst** [comment]
Shouldn't this be in your bundle test?

**Comment by ardatan** [comment]
The idea behind having this `bundle-test` is to check the size of this package inside a project. But we can add this kind of a test to have strict type checking for the library in point of another project. I'll take care of it. In addition, could you confirm it works for you?

**Comment by lookfirst** [comment]
I'll confirm it after you confirm it works on CI. ;-)

**Comment by ardatan** [comment]
@lookfirst You can create a PR to have this kind of test on CI.

**Comment by lookfirst** [comment]
![Aug-12-2019 19-08-40](https://user-images.githubusercontent.com/85355/62863992-abd01280-bd34-11e9-8b22-fd4cd87c80a9.gif)

**Comment by lookfirst** [comment]
fixed
