### ISSUE TITLE
JSON Array Scalar missing?

### ISSUE THREAD

**Issue by yoroshikun** [Urigo/graphql-scalars#662]
Hi,

I have been working with scalars for my personal project for a bit and have come across a slight limitation with the JSON Scalar

Essentially the data in the database is an array of objects, not directly an object eg. {}. vs [{},{}]. The ensureObject check then throws an error as it recognizes an array instead of an Object (as intended)

Is there a recommended way to represent and pass a JSON Array? For now, I have made a patch that removes the Array.isArray check which seems to parse the JSON Array just fine.

Might there be an option we can pass to disable Array checking to parse JSON Arrays with the JSON Scalar?

I might be missing something so, please let me know how to proceed. And I apologise in advance if it is a simple thing I'm missing.

**Comment by ardatan** [comment]
You mean arrays are not supported by JSON scalar. Arrays are also objects in JS so it should work anyway.

**Comment by yoroshikun** [comment]
> You mean arrays are not supported by JSON scalar. Arrays are also objects in JS so it should work anyway.

Yes that is what I mean, and the parser does work absolutely fine if i remove the specific `Array.isArray(value)` check in the ensureObject helper which runs before parsing the JSON.

How should I go about this without making that potentially dangerous modification to the ensureObject function.

**Comment by ardatan** [comment]
Oh ok now I see. I thought you were talking about `JSON` scalar but you are talking about `JSONObject`.  Would you create a PR that adds `JSONArray` scalar?

**Comment by yoroshikun** [comment]
I could give it a shot, Just wondering if that would be required. I guess it would be more type-safe than generic JSON.

So my options since JSON accepts arrays (I was mistakenly using JSONObject as the resolver) I could just use that. or. I can submit a PR that adds the JSONArray scalar that enforces array of objects?

Either or is fine for me. It was my mistake for using the JSONObject when clearly it was a JSON (which accepts arrays)

**Comment by ardatan** [comment]
I think using JSONObject by wrapping it in a list sounds better. Closing this then :)
