### ISSUE TITLE
Duplicate schema type name NonNegativeFloat in Resolver

### ISSUE THREAD

**Issue by dikatok** [Urigo/graphql-scalars#69]
Hi, I am using v1.0.0 and caught this error using a simple apollo server.

**Libs**
```
"graphql": "^14.4.2",
"graphql-scalars": "^1.0.0",
"merge-graphql-schemas": "^1.7.0",
"typescript": "^3.5.3"
```

**Server**
```
import { typeDefs as scalarTypeDefs } from 'graphql-scalars';
import { mergeTypes } from 'merge-graphql-schemas';

import { resolvers as scalarResolvers } from 'graphql-scalars';
import { mergeResolvers } from 'merge-graphql-schemas';

const typeDefs = mergeTypes([...scalarTypeDefs]);
const resolvers = mergeResolvers([scalarResolvers]);

const server = new ApolloServer({
  schema: makeExecutableSchema({
    typeDefs,
    resolvers,
    directiveResolvers
  }),
  context
});
```

**Error**
```
Error: Duplicate schema type name NonNegativeFloat
```

After investigating it, I found that there are 2 resolver definitions that share the same name `NonNegativeFloat`.

```
NonNegativeFloat: GraphQLScalarType {
    name: 'NonNegativeFloat',
    description: 'Floats that will have a value of 0 or more.',
    serialize: [Function: serialize],
    parseValue: [Function: parseValue],
    parseLiteral: [Function: parseLiteral],
    astNode: undefined,
    extensionASTNodes: undefined
  },
 UnsignedFloat: GraphQLScalarType {
    name: 'NonNegativeFloat',
    description: 'Floats that will have a value of 0 or more.',
    serialize: [Function: serialize],
    parseValue: [Function: parseValue],
    parseLiteral: [Function: parseLiteral],
    astNode: undefined,
    extensionASTNodes: undefined
  },
```

**EDIT:** Also happens with UnsignedInt, NonNegativeInt, BitInt, and Long.

Do I miss something else in my configuration?

**Comment by flasd** [comment]
I found three problems in the resolves: `UnsignedFloat`, `UnsignedInt` and `BigInt` have duplicate declarations.

Workaround:

```javascript
const { resolvers } = require('graphql-scalars');

module.exports = {
  ...resolvers,
};


delete module.exports.UnsignedFloat;
delete module.exports.UnsignedInt;
delete module.exports.BigInt;
```

delete module.exports.UnsignedFloat;
delete module.exports.UnsignedInt;
delete module.exports.BigInt;

And comment out the schema declarations

```javascript
# scalar UnsignedFloat
# scalar UnsignedInt
# scalar BigInt
```

**Comment by ardatan** [comment]
I tried to create a reproduction test which passes without any problems. 
https://github.com/Urigo/graphql-scalars/blob/82617d208f43cde1abf68e687fb16107d090b222/tests/reproduction-69.test.ts

**Comment by Urigo** [comment]
@dikatok @flasd if that still doesn't work for you, can you create a reproduction?

**Comment by ardatan** [comment]
@flasd This reproduction works without any errors. It's based on the code you sent
https://github.com/ardatan/graphql-scalars-flasd-issue-reprod

**Comment by dikatok** [comment]
@ardatan sorry for the late reply

confirmed working with no issue by casting to any, thanks :)

**Comment by ardatan** [comment]
You can see my example that uses that version.
