### ISSUE TITLE
Byte hexValidator returns false instead of true for hex value

### ISSUE THREAD

**Issue by rufman** [Urigo/graphql-scalars#716]
**Describe the bug**

Some hex values are not accepted by the hex validator as hex.

**To Reproduce**
```
const buf = Buffer.from([4, 8, 15, 16, 23, 42]);
const hex = buf.toString("hex");
console.log(hex); // 04080f10172a
console.log(hexValidator(hex)); // false
```

**Expected behavior**

A valid hex value should be identified as such

**Environment:**

- OS:
- GraphQL Scalars Version: 1.7.0
- NodeJS: 14.15

**Comment by ardatan** [comment]
Available in v1.7.1! Thanks @rufman !
