### ISSUE TITLE
Git hooks not working due to Husky V5 new config

### ISSUE THREAD

**Issue by carlocorradini** [Urigo/graphql-scalars#735]
**Describe the bug**
Husky V5 has changed the configuration/installation.
The git pre-commit hooks is not activated.
For more information: [https://dev.to/typicode/what-s-new-in-husky-5-32g5](https://dev.to/typicode/what-s-new-in-husky-5-32g5)

**To Reproduce**
Clone the repo. Change something. Commit.

**Expected behavior**
Git pre-commit hooks.

**Environment:**

- OS: Microsoft Windows 10 Pro 10.0.19042 Build 19042
- GraphQL Scalars Version: 1.7.1
- NodeJS: 12.13.1

**Comment by ardatan** [comment]
Fixed! Thanks for reporting this issue.
