### ISSUE TITLE
Add Latitude & Longitude scalars

### ISSUE THREAD

**Issue by carlocorradini** [Urigo/graphql-scalars#747]
Add Latitude & Longitude scalars.

Latitude: latitude is a geographic coordinate that specifies the north–south position of a point on the Earth's surface.

Longitude: is a geographic coordinate that specifies the east–west position of a point on the Earth's surface, or the surface of a celestial body.

**Comment by ardatan** [comment]
Available in https://github.com/Urigo/graphql-scalars/releases/tag/v1.9.0 !
Thanks @carlocorradini !
