### ISSUE TITLE
JSONObject: TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by iSplasher** [Urigo/graphql-scalars#760]
**Describe the bug**

Because of this line https://github.com/Urigo/graphql-scalars/blob/60190f594e2cbc37175d4364f44726e385dd70a0/src/scalars/json/utils.ts#L19
You'll get `TypeError: Cannot convert object to primitive value` when you try to print something like `console.log(``${Object.create(null)}``)` because it doesn't inherit from `Object`.

Unless there's a good reason to not create a normal object, i suggest fixing this just by assigning a plain `{}` instead.
`JSON.parse("{}")` produces a normal Object so I think the same behavior should be expected here.

**To Reproduce**
Try and print a parsed literal like `{}` like this `console.log(``${JSONResolver.parseLiteral("{}")}``)`

**Expected behavior**

No error is thrown and it gets formatted correctly

**Environment:**

- OS:
- GraphQL Scalars Version:
- NodeJS:

**Additional context**

Thanks for the library

**Comment by ardatan** [comment]
Could you create a PR with a failing test?

**Comment by ardatan** [comment]
Closing due to the inactivity. Feel free to create a new issue with a reproduction.
You can also check this;
[issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)
