### ISSUE TITLE
In nestjs, showing the following error. 

### ISSUE THREAD

**Issue by rakibulalam** [Urigo/graphql-scalars#805]
`Type '{ Date: GraphQLScalarType; Time: GraphQLScalarType; DateTime: GraphQLScalarType; Timestamp: GraphQLScalarType; ... 47 more ...; Void: GraphQLScalarType; }' must have a '[Symbol.iterator]()' method that returns an iterator.ts(2488)`

**Comment by ardatan** [comment]
Could you give more details and create another issue with a reproduction if possible. GraphQL Scalars package exports scalars as `GraphQLScalarType`. So it is independent from the framework you use.
