### ISSUE TITLE
[Website] graphql-scalars.dev not viewable, error: NET::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by hinsxd** [Urigo/graphql-scalars#825]
**Describe the bug**

https://www.graphql-scalars.dev is OK but https://graphql-scalars.dev is not

```
Your connection is not private
Attackers might be trying to steal your information from graphql-scalars.dev (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID
```

**To Reproduce**
https://graphql-scalars.dev

**Environment:**

- OS: MacOS 10.15.7

**Additional context**
Perhaps some problems in setting subdomians for the certificates. Not familiar in domain settings

**Comment by ardatan** [comment]
This seems fixed! Thank you for reporting this!
