### ISSUE TITLE
Website looks blurry on Windows Firefox 

### ISSUE THREAD

**Issue by tw0517tw** [Urigo/graphql-scalars#846]
**Describe the bug**
The website looks blurry. Screenshots below.

**To Reproduce**

Use Firefox 89.0b7 (I'm on beta channel), open https://www.graphql-scalars.dev/docs/introduction/ or https://www.graphql-scalars.dev/
It looks good if I use Chrome instead.

**Expected behavior**

It should look clear

**Environment:**

- OS: Windows 10 20H2
- Firefox: 89.0b7

**Additional context**

![圖片](https://user-images.githubusercontent.com/1003146/116986985-11caad80-ad01-11eb-878b-09dac9a34403.png)
![圖片](https://user-images.githubusercontent.com/1003146/116987060-29a23180-ad01-11eb-90e5-3ec075653dad.png)

**Comment by ardatan** [comment]
I don't have that issue on my Windows environment
![image](https://user-images.githubusercontent.com/20847995/117003605-0e103a00-acb3-11eb-8e3d-91553a96912e.png)
Maybe it is an issue on Firefox's beta version.

**Comment by ardatan** [comment]
Closing this issue for now. Let us know if it persists.
