### ISSUE TITLE
Empty string is an invalid URL

### ISSUE THREAD

**Issue by LucienLee** [Urigo/graphql-scalars#870]
**Describe the bug**
Pass empty string is legal in the current URL scalar. However, according to https://www.ietf.org/rfc/rfc3986.txt, it should not be empty.

I wonder that it's expected that URL scalar accepts `''`.  If it's not what we expected, I can make PR

**Expected behavior**
Throw error when passing empty string to URL scalar

**Comment by ardatan** [comment]
We'd love to accept a PR to fix this :)
