### ISSUE TITLE
Modularize scalars

### ISSUE THREAD

**Issue by ravangen** [Urigo/graphql-scalars#90]
A possible future improvement would be to enable cherry picking specific scalars to import. This could be similar to`lodash` which publishes both the complete package and per method packages.

Having this library is great for standardization across the community, but some scalars are more niche and something I would prefer to be able to exclude if possible.

```typescript
import merge from 'lodash.merge';

import URLResolver from 'graphql-scalars.url';
```

**Comment by ardatan** [comment]
We already have this. You need to import ‘SomeDefinition’ and ‘SomeResolver’ for example.

**Comment by ravangen** [comment]
I was meaning separate NPM packages. For example, there is [`lodash`](https://www.npmjs.com/package/lodash) and [`lodash.merge`](https://www.npmjs.com/package/lodash.merge). I am aware I don't need to import everything from the `graphql-scalars` module. 

I thought it could be a nice to have feature request, obviously not critical. This "issue" can stay closed regardless. Seemingly this package will grow to encase a variety of scalars, and this would enable being more selective about what dependencies are actually necessary to support each scalar.

**Comment by ardatan** [comment]
@ravangen We can keep it open :) Sorry for misunderstanding. That would be a nice feature

**Comment by httpiago** [comment]
You don't need to separate into multiple packages, it's unnecessary complexity for the maintainer, just separating into [subfolders](https://nodejs.org/api/modules.html#modules_loading_from_node_modules_folders) solves the problem:

```js
import { typeDefs, resolver } from 'graphql-scalars/URL'
import { typeDefs, resolver } from 'graphql-scalars/PhoneNumber'
```

**Comment by ardatan** [comment]
@ravangen @httpiago This package is already tree-shakable so is it a specific reason for this?

**Comment by ravangen** [comment]
We can close this, I don't think it is worth any extra process overhead on the maintainers.

I had been using `lodash` the other day and had simply thought that their option to use separate micro packages was a nice feature. 90% of these scalars don't apply to my current uses cases.

**Comment by dburles** [comment]
Why is the package bundled? Don't bundle it and allow consumers to deep import the parts they need. That way we're not needlessly loading 3000+ lines of source code into memory just for the sake of a single scalar.

**Comment by ardatan** [comment]
All scalars are treeshakable. You can use a bundler like `webpack` if the bundle size is important for you.
We're still open for PRs for more :)

**Comment by dburles** [comment]
Of course, but the other benefit is that consumers won't be required to bundle and tree-shake.
